In [1]:
import numpy as np # 
import pandas as pd 
import requests, io 
import glob
from pprint import pprint
import matplotlib.pyplot as plt 
import random
import time
%matplotlib inline

# scikit-learn modules
from sklearn.model_selection import train_test_split 
from sklearn.metrics import mean_squared_error 
from sklearn.ensemble import RandomForestRegressor 
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.preprocessing import StandardScaler
from sklearn.utils import shuffle
class color:
   PURPLE = '\033[95m'
   CYAN = '\033[96m'
   DARKCYAN = '\033[36m'
   BLUE = '\033[94m'
   GREEN = '\033[92m'
   YELLOW = '\033[93m'
   RED = '\033[91m'
   BOLD = '\033[1m'
   UNDERLINE = '\033[4m'
   END = '\033[0m'

C:\Users\anilo\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [11]:
df=pd.read_csv(r'E:\Havelsan\Datasets\M0000_train_sensors.csv', engine='c')

In [12]:
df['Load'].unique()

array(['FAL', 'FAU'], dtype=object)

In [13]:
SeaTemp='SW20'
WindSpeed='WC0'
Load='FAL'
df=df[df['SeaTemp']==SeaTemp]
df=df[df['WindSpeed']==WindSpeed]
df=df[df['Load']==Load]
result=df
result.dropna(inplace=True)
result.reset_index(drop=True,inplace=True)
abr_sensor_list = ['E02005', 'E02006', 'E02056', 'E03760', 'G00027', 'G00108', 'G02011', 'N02015', 'P00023', 'P01005', 'P01302', 'P01303', 'P01600', 'P01602', 'P02055', 'P02065', 'P02066', 'P02071', 'P02072', 'Q02004', 'T00002', 'T01010', 'T01011', 'T01350', 'T01351', 'T01601', 'T01603', 'T02014', 'T02040', 'T02041', 'T02042', 'T02044', 'T04600', 'Z00518', 'Z01970', 'Z02013']
df_sample=result[abr_sensor_list]
X = df_sample.drop('Z02013', axis = 1) # Features
y = df_sample['Z02013']  # Target

In [14]:
df_sample

E02005   E02006   E02056   E03760   G00027   G00108   G02011   N02015  \
0      16.7659  430.912  3647.98  16.5258  3.17649  3.43147  3.17649  74.0058   
1      16.7659  430.912  3647.98  16.5258  3.17649  3.43147  3.17649  74.0058   
2      16.7659  430.912  3647.98  16.5258  3.17649  3.43147  3.17649  74.0058   
3      16.7659  430.912  3647.98  16.5258  3.17649  3.43147  3.17649  74.0058   
4      16.7659  430.912  3647.98  16.5258  3.17649  3.43147  3.17649  74.0058   
...        ...      ...      ...      ...      ...      ...      ...      ...   
43218  16.7617  370.980  3660.98  16.5173  3.16089  3.41246  3.16089  74.0017   
43219  16.7617  369.984  3660.98  16.5173  3.16089  3.41246  3.16089  74.0017   
43220  16.7617  368.987  3660.98  16.5173  3.16089  3.41246  3.16089  74.0017   
43221  16.7617  367.990  3660.98  16.5173  3.16089  3.41246  3.16089  74.0017   
43222  16.7617  366.993  3660.98  16.5173  3.16089  3.41246  3.16089  74.0017   

        P00023   P01005  ...   T01603   T02014   T02040   T02041   T02042  \
0      7.63919  2.15155  ...  371.789  325.643  324.319 -1.31793  46.7306   
1      7.63919  2.15155  ...  371.789  325.643  324.319 -1.31793  46.7306   
2      7.63919  2.15155  ...  371.789  325.643  324.319 -1.31793  46.7306   
3      7.63919  2.15155  ...  371.789  325.643  324.319 -1.31793  46.7306   
4      7.63919  2.15155  ...  371.789  325.643  324.319 -1.31793  46.7306   
...        ...      ...  ...      ...      ...      ...      ...      ...   
43218  7.64350  2.14795  ...  371.102  324.938  323.561 -1.37216  46.7115   
43219  7.64350  2.14799  ...  371.155  324.948  323.566 -1.37807  46.7205   
43220  7.64350  2.14803  ...  371.207  324.958  323.572 -1.38399  46.7295   
43221  7.64350  2.14808  ...  371.260  324.968  323.577 -1.38990  46.7385   
43222  7.64350  2.14812  ...  371.312  324.979  323.583 -1.39581  46.7475   

        T02044   T04600   Z00518   Z01970   Z02013  
0      48.6324  234.325  12.9311  14.9813  22.5320  
1      48.6324  234.325  12.9311  14.9813  22.5320  
2      48.6324  234.325  12.9311  14.9813  22.5320  
3      48.6324  234.325  12.9311  14.9813  22.5320  
4      48.6324  234.325  12.9311  14.9813  22.5320  
...        ...      ...      ...      ...      ...  
43218  48.6358  233.896  12.9154  15.0387  22.4346  
43219  48.6358  233.896  12.9154  15.0393  22.4312  
43220  48.6358  233.896  12.9154  15.0398  22.4278  
43221  48.6358  233.896  12.9154  15.0404  22.4244  
43222  48.6358  233.896  12.9154  15.0410  22.4210  

[43223 rows x 36 columns]

In [5]:
X

E02005   E02006    E02056   E03760   G00027   G00108   G02011  \
0      14.0904  266.676     0.000  13.8741  2.62669  2.83482  2.62672   
1      14.0904  266.676     0.000  13.8741  2.62669  2.83482  2.62672   
2      13.9726  347.270     0.000  13.7390  2.65347  2.83482  2.65506   
3      13.9819  341.611   225.204  13.7495  2.65172  2.83517  2.65320   
4      13.9912  335.952   450.408  13.7600  2.64996  2.83553  2.65133   
...        ...      ...       ...      ...      ...      ...      ...   
44323  14.0962  248.142  3130.950  13.8798  2.62351  2.83302  2.62349   
44324  14.0959  247.351  3130.950  13.8795  2.62332  2.83285  2.62331   
44325  14.0957  246.561  3130.950  13.8791  2.62314  2.83269  2.62313   
44326  14.0955  245.770  3130.950  13.8788  2.62295  2.83253  2.62295   
44327  14.0953  244.979  3130.950  13.8784  2.62277  2.83237  2.62277   

        N02015   P00023   P01005  ...   T01601   T01603   T02014   T02040  \
0      74.0005  7.78959  2.15359  ...  43.5334  348.143  305.317  303.497   
1      74.0005  7.78959  2.15359  ...  43.5334  348.143  305.317  303.497   
2      73.9091  7.78951  2.15389  ...  43.5334  348.511  305.317  303.516   
3      73.9162  7.78946  2.15398  ...  43.5331  348.499  305.333  303.529   
4      73.9233  7.78941  2.15406  ...  43.5328  348.486  305.349  303.541   
...        ...      ...      ...  ...      ...      ...      ...      ...   
44323  74.0017  7.79047  2.15608  ...  43.5323  348.257  305.562  304.118   
44324  74.0017  7.79052  2.15602  ...  43.5323  348.233  305.563  304.121   
44325  74.0017  7.79057  2.15596  ...  43.5323  348.209  305.564  304.123   
44326  74.0017  7.79062  2.15590  ...  43.5323  348.185  305.565  304.126   
44327  74.0017  7.79068  2.15584  ...  43.5323  348.161  305.566  304.128   

        T02041   T02042   T02044   T04600   Z00518   Z01970  
0     -1.81976  43.7985  48.0050  220.359  12.8062  12.8297  
1     -1.81976  43.7985  48.0050  220.359  12.8062  12.8297  
2     -1.81976  43.7985  48.0050  220.364  12.8062  12.9007  
3     -1.82216  43.7888  48.0049  220.367  12.8062  12.8980  
4     -1.82455  43.7792  48.0047  220.370  12.8063  12.8954  
...        ...      ...      ...      ...      ...      ...  
44323 -1.44776  43.8632  48.0087  220.446  12.8043  12.7994  
44324 -1.44473  43.8563  48.0087  220.451  12.8043  12.7970  
44325 -1.44170  43.8493  48.0087  220.457  12.8043  12.7945  
44326 -1.43867  43.8423  48.0087  220.463  12.8043  12.7921  
44327 -1.43564  43.8354  48.0087  220.468  12.8043  12.7896  

[44328 rows x 35 columns]

In [6]:
y

0        19.9715
1        19.9715
2        20.7326
3        20.6785
4        20.6244
          ...   
44323    19.9814
44324    19.9814
44325    19.9814
44326    19.9814
44327    19.9814
Name: Z02013, Length: 44328, dtype: float64

# K-fold cross validation

In [8]:
# Define the number of folds
k = 5

# Randomly shuffle the indices of the data
indices = np.arange(X.shape[0])
np.random.shuffle(indices)

# Split the indices into k groups
indices = np.array_split(indices, k)

# Perform k-fold cross-validation
accuracies = []


In [9]:
indices

[array([26280, 44253, 34688, ..., 34560,  7100, 12750]),
 array([25743, 19246,  8467, ..., 29652, 21198, 41186]),
 array([28862, 39537, 21426, ..., 42890, 33489,  8085]),
 array([42693, 22329,  3913, ..., 32047, 37022, 31610]),
 array([27475, 29043, 18920, ...,  4953, 40669,  6684])]

In [10]:
for i in range(k):
    # Prepare the test set indices
    test_indices = indices[i]
    
    # Prepare the training set indices
    train_indices = np.concatenate([indices[j] for j in range(k) if j != i])
    
    # Get the training and test sets
    X_train, X_test = X.iloc[train_indices], X.iloc[test_indices]
    y_train, y_test = y.iloc[train_indices], y.iloc[test_indices]
    # Initializing the Random Forest Regression model with 10 decision trees
    model = RandomForestRegressor(n_estimators = 10, random_state = 0)

    # Fitting the Random Forest Regression model to the data
    model.fit(X_train, y_train)
    # Test the model
    y_pred = model.predict(X_test)
    
    # Calculate the accuracy and append it to the list
    accuracy = np.sqrt(mean_squared_error(y_test, y_pred))
    accuracies.append(accuracy)

In [11]:
# Print the average accuracy
print("Average accuracy: ", np.mean(accuracies))

Average accuracy:  0.003821832393700471


# Randomized Search

In [12]:
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
max_features = ['auto', 'sqrt','log2']
max_depth = [int(x) for x in np.linspace(10, 1000,10)]
min_samples_split = [2, 5, 10,14]
min_samples_leaf = [1, 2, 4,6,8]

In [13]:
model = RandomForestRegressor()
best_score = np.inf
n_iterations = 10
# Splitting the dataset into training and testing set (80/20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 28)
for i in range(n_iterations):
    start_time = time.time()
    # Select a random values for parameters
    n_estimator = random.choice(n_estimators)
    max_feature = random.choice(max_features)
    max_dep = random.choice(max_depth)
    min_samples_spl = random.choice(min_samples_split)
    min_samples_lf = random.choice(min_samples_leaf)
    # Set parameters to model
    model.set_params(n_estimators=n_estimator, max_features=max_feature, max_depth=max_dep, min_samples_split=min_samples_spl, min_samples_leaf=min_samples_lf)
    
    # Fit model on training data
    model.fit(X_train, y_train)
    paramaters_dict={'n_estimator':n_estimator,'max_feature':max_feature,'max_dep':max_dep,'min_samples_spl':min_samples_spl,'min_samples_lf':min_samples_lf}
    # Make predictions and get the error
    predictions = model.predict(X_test)
    error = np.sqrt(mean_squared_error(y_test, predictions))
    # If the score of the current iteration is better than best recorded so far, update best_score and best_params
    if error < best_score:
        best_score = error
        best_params = {"n_estimators": n_estimator, "max_features": max_feature, "max_depth": max_dep, "min_samples_split": min_samples_spl, "min_samples_leaf": min_samples_lf}
    end_time = time.time()
    iteration_time = end_time - start_time
    print(color.BOLD)
    print("------------------------------------------------------------------------------------------------------")
    print("Iteration {0} took {1} seconds.".format(i, iteration_time))
    print(paramaters_dict)
    print("root_mean_squared_error: ",error)
    print("------------------------------------------------------------------------------------------------------")
    print(color.END)
print("Best parameters found: ", best_params)
print("Lowest RMSE found: ",(best_score))


------------------------------------------------------------------------------------------------------
Iteration 0 took 175.50984907150269 seconds.
{'n_estimator': 1200, 'max_feature': 'sqrt', 'max_dep': 340, 'min_samples_spl': 10, 'min_samples_lf': 2}
root_mean_squared_error:  0.0048655424254048845
------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------
Iteration 1 took 131.35676336288452 seconds.
{'n_estimator': 800, 'max_feature': 'sqrt', 'max_dep': 780, 'min_samples_spl': 2, 'min_samples_lf': 1}
root_mean_squared_error:  0.0038785790293693148
------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------
Iteration 2 took 26.270431995391846 seconds.
{'n_estimator': 200, 'max_feature': 'sqrt

# Randomized Search with K-fold cross validation


In [7]:
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
max_features = ['auto', 'sqrt','log2']
max_depth = [int(x) for x in np.linspace(10, 1000,10)]
min_samples_split = [2, 5, 10,14]
min_samples_leaf = [1, 2, 4,6,8]

In [9]:
# Define your model 
model = RandomForestRegressor()

# Assuming X_train, y_train are already defined
best_score = np.inf

# Number of iterations for the search
n_iterations = 10
k = 5
# Randomly shuffle the indices of the data
indices = np.arange(X.shape[0])
np.random.shuffle(indices)

# Split the indices into k groups
indices = np.array_split(indices, k)

# Perform k-fold cross-validation
accuracies = []

for i in range(n_iterations):
    start_time = time.time()
    # Select a random values for parameters
    n_estimator = random.choice(n_estimators)
    max_feature = random.choice(max_features)
    max_dep = random.choice(max_depth)
    min_samples_spl = random.choice(min_samples_split)
    min_samples_lf = random.choice(min_samples_leaf)
    # Set parameters to model
    model.set_params(n_estimators=n_estimator, max_features=max_feature, max_depth=max_dep, min_samples_split=min_samples_spl, min_samples_leaf=min_samples_lf)
    paramaters_dict = {"n_estimators": n_estimator, "max_features": max_feature, "max_depth": max_dep, "min_samples_split": min_samples_spl, "min_samples_leaf": min_samples_lf}
    # Perform k-fold cross-validation
    accuracies = []
    for v in range(k):
        # Prepare the test set indices
        test_indices = indices[v]

        # Prepare the training set indices
        train_indices = np.concatenate([indices[j] for j in range(k) if j != v])

        # Get the training and test sets
        X_train, X_test = X.iloc[train_indices], X.iloc[test_indices]
        y_train, y_test = y.iloc[train_indices], y.iloc[test_indices]
        # Initializing the Random Forest Regression model with 10 decision trees
        # Fitting the Random Forest Regression model to the data
        model.fit(X_train, y_train)
        # Test the model
        y_pred = model.predict(X_test)

        # Calculate the accuracy and append it to the list
        accuracy = np.sqrt(mean_squared_error(y_test, y_pred))
        accuracies.append(accuracy)
    error = np.mean(accuracies)
    if error < best_score:
        best_score = error
        best_params = {"n_estimators": n_estimator, "max_features": max_feature, "max_depth": max_dep, "min_samples_split": min_samples_spl, "min_samples_leaf": min_samples_lf}
    end_time = time.time()
    iteration_time = end_time - start_time
    print(color.BOLD)
    print("------------------------------------------------------------------------------------------------------")
    print("Iteration {0} took {1} seconds.".format(i, iteration_time))
    print(paramaters_dict)
    print("root_mean_squared_error: ",error)
    print("------------------------------------------------------------------------------------------------------")
    print(color.END)
print("Best parameters found: ", best_params)
print("Lowest RMSE found: ",(best_score))
        


------------------------------------------------------------------------------------------------------
Iteration 0 took 544.0662117004395 seconds.
{'n_estimators': 800, 'max_features': 'log2', 'max_depth': 1000, 'min_samples_split': 5, 'min_samples_leaf': 8}
root_mean_squared_error:  0.0071225442737135065
------------------------------------------------------------------------------------------------------



KeyboardInterrupt: 